/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Mis Documentos
 */
public class Categorias extends javax.swing.JFrame {

    /**
     * Creates new form Categorias
     */
    public Categorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCategoriaidCA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcionCA = new javax.swing.JTextField();
        btnEditarCA = new javax.swing.JButton();
        btnAgregarCA = new javax.swing.JButton();
        btnEliminarCA = new javax.swing.JButton();
        btnLimpiarCA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCategorias = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegresarCA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(35, 155, 86));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("ADMINISTRADOR DE CATEGORIAS");

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("Categoria ID:");

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("Descripcion");

        btnEditarCA.setBackground(new java.awt.Color(255, 102, 0));
        btnEditarCA.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnEditarCA.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCA.setText("Editar");
        btnEditarCA.setBorder(null);
        btnEditarCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarCAMouseClicked(evt);
            }
        });

        btnAgregarCA.setBackground(new java.awt.Color(255, 102, 0));
        btnAgregarCA.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnAgregarCA.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCA.setText("Agregar");
        btnAgregarCA.setBorder(null);
        btnAgregarCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarCAMouseClicked(evt);
            }
        });

        btnEliminarCA.setBackground(new java.awt.Color(255, 102, 0));
        btnEliminarCA.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnEliminarCA.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCA.setText("Eliminar");
        btnEliminarCA.setBorder(null);
        btnEliminarCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarCAMouseClicked(evt);
            }
        });

        btnLimpiarCA.setBackground(new java.awt.Color(255, 102, 0));
        btnLimpiarCA.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnLimpiarCA.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCA.setText("Limpiar");
        btnLimpiarCA.setBorder(null);
        btnLimpiarCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarCAMouseClicked(evt);
            }
        });

        TablaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCION"
            }
        ));
        TablaCategorias.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablaCategorias.setRowHeight(25);
        TablaCategorias.setSelectionBackground(new java.awt.Color(255, 102, 0));
        TablaCategorias.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TablaCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCategorias);

        jLabel8.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 51));
        jLabel8.setText("Lista de Categorias");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAgregarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(btnLimpiarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(txtCategoriaidCA, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(47, 47, 47)
                        .addComponent(txtNombreCA, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcionCA, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtCategoriaidCA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreCA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(txtDescripcionCA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");

        btnRegresarCA.setBackground(new java.awt.Color(255, 102, 0));
        btnRegresarCA.setFont(new java.awt.Font("Poppins SemiBold", 1, 48)); // NOI18N
        btnRegresarCA.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarCA.setText("<");
        btnRegresarCA.setBorder(null);
        btnRegresarCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarCAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarCA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCAMouseClicked
        // TODO add your handling code here:
//        if(txtCategoriaCA.getText().isEmpty()||txtNombreCA.getText().isEmpty()||txtDescripcionCA.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Informacion faltante");
//        }else{
//            try{
//                Con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/SellerTBL","postgres","1234");
//                String Query = "Update User1.CATEGORYTBL set CATNAME='"+txtNombreCA.getText()+"'"+",CATDESC='"+txtDescripcionCA.getText()+"'"+"where CATID="+txtCategoriaCA.getText();
//                Statement Add = Con.createStatement();
//                Add.executeUpdate(Query);
//                JOptionPane.showMessageDialog(this, "Categoria actualizada");
//                SelectSeller();
//            }catch(SQLException e){
//                e.printStackTrace();
//            }
//        }

    }//GEN-LAST:event_btnEditarCAMouseClicked

    private void btnAgregarCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCAMouseClicked
        // TODO add your handling code here:
//        if(txtCategoriaCA.getText().isEmpty()|| txtNombreCA.getText().isEmpty()||txtDescripcionCA.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Informacion Faltante");
//        }
//        else{
//            try {
//                //Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Supermarket","null","null");
//                Con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/SellerTBL","postgres","1234");
//                PreparedStatement add = Con.prepareStatement("insert into CATEGORYRTBL values(?,?,?)");
//                add.setInt(1, Integer.valueOf(txtCategoriaCA.getText()));
//                add.setString(2, txtNombreCA.getText());
//                add.setString(3, txtDescripcionCA.getText());
//
//                int row = add.executeUpdate();
//                JOptionPane.showMessageDialog(this, "Categoria agregado con exito");
//                Con.close();
//                SelectSeller();
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
    }//GEN-LAST:event_btnAgregarCAMouseClicked

    private void btnEliminarCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCAMouseClicked
//        // TODO add your handling code here:
//        if (txtCategoriaCA.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Introduzca la categoria que se eliminará");
//        }else{
//            try{
//                Con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/SellerTBL","postgres","1234");
//                String Cid = txtCategoriaCA.getText();
//                String Query = "Delete from User1.CATEGORYTBL where CATID="+Cid;
//                Statement Add = Con.createStatement();
//                Add.execute(Query);
//                SelectSeller();
//                JOptionPane.showMessageDialog(this, "Categoria eleimiando satisfactoriamente");
//            }catch(Exception e){
//                e.printStackTrace();
//            }
//
//        }
    }//GEN-LAST:event_btnEliminarCAMouseClicked

    private void btnLimpiarCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarCAMouseClicked
        // TODO add your handling code here:
        txtCategoriaidCA.setText("");
        txtNombreCA.setText("");
        txtDescripcionCA.setText("");
    }//GEN-LAST:event_btnLimpiarCAMouseClicked

    private void TablaCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCategoriasMouseClicked
        // TODO add your handling code here:
//        DefaultTableModel model = (DefaultTableModel)TablaCategorias.getModel();
//        int Myindex = TablaCategorias.getSelectedRow();
//        txtCategoriaCA.setText(model.getValueAt(Myindex, 0).toString());
//        txtNombreCA.setText(model.getValueAt(Myindex, 1).toString());
//        txtDescripcionCA.setText(model.getValueAt(Myindex, 2).toString());
    }//GEN-LAST:event_TablaCategoriasMouseClicked

    private void btnRegresarCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarCAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarCAMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn2;
    private javax.swing.JButton Addbtn3;
    private javax.swing.JTable TablaCategorias;
    private javax.swing.JButton btnAgregarCA;
    private javax.swing.JButton btnEditarCA;
    private javax.swing.JButton btnEliminarCA;
    private javax.swing.JButton btnLimpiarCA;
    private javax.swing.JButton btnRegresarCA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCategoriaidCA;
    private javax.swing.JTextField txtDescripcionCA;
    private javax.swing.JTextField txtNombreCA;
    // End of variables declaration//GEN-END:variables
}
