/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Mis Documentos
 */
public class EmpleadosRegistrados extends javax.swing.JFrame {

    /**
     * Creates new form EmpleadosRegistrados
     */
    public EmpleadosRegistrados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCedulaER = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleadosRegistrados = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBuscarER = new javax.swing.JButton();
        btnLimpiarER = new javax.swing.JButton();
        btnVisualizarER = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRegresarER = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(35, 155, 86));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("EMPLEADOS REGISTRADOS");

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("Cedula:");

        TablaEmpleadosRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CONTRASEÑA", "GENERO"
            }
        ));
        TablaEmpleadosRegistrados.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablaEmpleadosRegistrados.setRowHeight(25);
        TablaEmpleadosRegistrados.setSelectionBackground(new java.awt.Color(255, 102, 0));
        TablaEmpleadosRegistrados.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TablaEmpleadosRegistrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEmpleadosRegistradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaEmpleadosRegistrados);

        jLabel8.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 51));
        jLabel8.setText("Lista de Empleados");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnBuscarER.setBackground(new java.awt.Color(255, 102, 0));
        btnBuscarER.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnBuscarER.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarER.setText("Buscar");
        btnBuscarER.setBorder(null);
        btnBuscarER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarERMouseClicked(evt);
            }
        });

        btnLimpiarER.setBackground(new java.awt.Color(255, 102, 0));
        btnLimpiarER.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnLimpiarER.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarER.setText("Limpiar");
        btnLimpiarER.setBorder(null);
        btnLimpiarER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarERMouseClicked(evt);
            }
        });

        btnVisualizarER.setBackground(new java.awt.Color(255, 102, 0));
        btnVisualizarER.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnVisualizarER.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizarER.setText("Visualizar Todos");
        btnVisualizarER.setBorder(null);
        btnVisualizarER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisualizarERMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnBuscarER, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnLimpiarER, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnVisualizarER, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarER, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarER, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisualizarER, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedulaER, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(363, 363, 363))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3))
                            .addComponent(txtCedulaER, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        btnRegresarER.setBackground(new java.awt.Color(255, 102, 0));
        btnRegresarER.setFont(new java.awt.Font("Poppins SemiBold", 1, 48)); // NOI18N
        btnRegresarER.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarER.setText("<");
        btnRegresarER.setBorder(null);
        btnRegresarER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarERMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarER, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarER, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnVisualizarERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarERMouseClicked
//        // TODO add your handling code here:
//        if (Selid.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Introduzca la vendedora que se eliminará");
//        }else{
//            try{
//                Con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/SellerTBL","postgres","1234");
//                String Sid = Selid.getText();
//                String Query = "Delete from User1.SELLERTBL where Selid="+Sid;
//                Statement Add = Con.createStatement();
//                Add.execute(Query);
//                SelectSeller();
//                JOptionPane.showMessageDialog(this, "vendedor eleimiando satisfactoriamente");
//            }catch(Exception e){
//                e.printStackTrace();
//            }
//
//        }
    }//GEN-LAST:event_btnVisualizarERMouseClicked

    private void btnLimpiarERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarERMouseClicked
       txtCedulaER.setText("");
    }//GEN-LAST:event_btnLimpiarERMouseClicked

    private void btnBuscarERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarERMouseClicked
//        // TODO add your handling code here:
//        if(Selid.getText().isEmpty()|| txtCedulaER.getText().isEmpty()||SelPass.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Informacion Faltante");
//        }
//        else{
//            try {
//                //Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Supermarket","null","null");
//                Con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/SellerTBL","postgres","1234");
//                PreparedStatement add = Con.prepareStatement("insert into SELLERTBL values(?,?,?,?)");
//                add.setInt(1, Integer.valueOf(Selid.getText()));
//                add.setString(2, txtCedulaER.getText());
//                add.setString(3, SelPass.getText());
//                add.setString(4, GenderCB.getSelectedItem().toString());
//                int row = add.executeUpdate();
//                JOptionPane.showMessageDialog(this, "Vendedor agregado con exito");
//                Con.close();
//                SelectSeller();
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
    }//GEN-LAST:event_btnBuscarERMouseClicked

    private void TablaEmpleadosRegistradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEmpleadosRegistradosMouseClicked
//        // TODO add your handling code here:
//        DefaultTableModel model = (DefaultTableModel)TablaEmpleadosRegistrados.getModel();
//        int Myindex = TablaEmpleadosRegistrados.getSelectedRow();
//        Selid.setText(model.getValueAt(Myindex, 0).toString());
//        txtCedulaER.setText(model.getValueAt(Myindex, 1).toString());
//        SelPass.setText(model.getValueAt(Myindex, 2).toString());
    }//GEN-LAST:event_TablaEmpleadosRegistradosMouseClicked

    private void btnRegresarERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarERMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarERMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadosRegistrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadosRegistrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadosRegistrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadosRegistrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadosRegistrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaEmpleadosRegistrados;
    private javax.swing.JButton btnBuscarER;
    private javax.swing.JButton btnLimpiarER;
    private javax.swing.JButton btnRegresarER;
    private javax.swing.JButton btnVisualizarER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCedulaER;
    // End of variables declaration//GEN-END:variables
}
