/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Mis Documentos
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProductoIDPRO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombrePRO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidadPRO = new javax.swing.JTextField();
        txtPrecioPRO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxPRO = new javax.swing.JComboBox<>();
        btnEditarPRO = new javax.swing.JButton();
        btnAgregarPRO = new javax.swing.JButton();
        btnEliminarPRO = new javax.swing.JButton();
        btnLimpiarPRO = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_fotoPRO = new javax.swing.JLabel();
        btnExaminarPRO = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRegresarPRO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(35, 155, 86));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("ADMINISTRADOR DE PRODUCTOS");

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("Producto ID:");

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("Cantidad:");

        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setText("Precio:");

        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("Categoria:");

        btnEditarPRO.setBackground(new java.awt.Color(255, 102, 0));
        btnEditarPRO.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnEditarPRO.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPRO.setText("Editar");
        btnEditarPRO.setBorder(null);
        btnEditarPRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarPROMouseClicked(evt);
            }
        });

        btnAgregarPRO.setBackground(new java.awt.Color(255, 102, 0));
        btnAgregarPRO.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnAgregarPRO.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPRO.setText("Agregar");
        btnAgregarPRO.setBorder(null);
        btnAgregarPRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPROMouseClicked(evt);
            }
        });

        btnEliminarPRO.setBackground(new java.awt.Color(255, 102, 0));
        btnEliminarPRO.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnEliminarPRO.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPRO.setText("Eliminar");
        btnEliminarPRO.setBorder(null);
        btnEliminarPRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPROMouseClicked(evt);
            }
        });

        btnLimpiarPRO.setBackground(new java.awt.Color(255, 102, 0));
        btnLimpiarPRO.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnLimpiarPRO.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarPRO.setText("Limpiar");
        btnLimpiarPRO.setBorder(null);
        btnLimpiarPRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarPROMouseClicked(evt);
            }
        });

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CANTIDAD", "PRECIO", "CATEGORIA"
            }
        ));
        TablaProductos.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablaProductos.setRowHeight(25);
        TablaProductos.setSelectionBackground(new java.awt.Color(255, 102, 0));
        TablaProductos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProductos);

        jLabel8.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 51));
        jLabel8.setText("Lista de Productos");

        jLabel9.setFont(new java.awt.Font("Poppins SemiBold", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 51));
        jLabel9.setText("Elija una imagen:");

        lbl_fotoPRO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnExaminarPRO.setBackground(new java.awt.Color(255, 102, 0));
        btnExaminarPRO.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnExaminarPRO.setForeground(new java.awt.Color(255, 255, 255));
        btnExaminarPRO.setText("Examinar....");
        btnExaminarPRO.setBorder(null);
        btnExaminarPRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExaminarPROMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtProductoIDPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombrePRO, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addGap(31, 31, 31)
                                    .addComponent(ComboBoxPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32)
                                .addComponent(txtCantidadPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(txtPrecioPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fotoPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(btnExaminarPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnAgregarPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(308, 308, 308))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_fotoPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExaminarPRO))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtProductoIDPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtNombrePRO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtCantidadPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecioPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ComboBoxPRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        btnRegresarPRO.setBackground(new java.awt.Color(255, 102, 0));
        btnRegresarPRO.setFont(new java.awt.Font("Poppins SemiBold", 1, 48)); // NOI18N
        btnRegresarPRO.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarPRO.setText("<");
        btnRegresarPRO.setBorder(null);
        btnRegresarPRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarPROMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarPRO, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnExaminarPROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExaminarPROMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExaminarPROMouseClicked

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked
//        // TODO add your handling code here:
//        DefaultTableModel model = (DefaultTableModel)TablaProductos.getModel();
//        int Myindex = TablaProductos.getSelectedRow();
//        txtProductoIDPRO.setText(model.getValueAt(Myindex, 0).toString());
//        txtNombrePRO.setText(model.getValueAt(Myindex, 1).toString());
//        txtCantidadPRO.setText(model.getValueAt(Myindex, 2).toString());
//        txtPrecioPRO.setText(model.getValueAt(Myindex, 3).toString());
    }//GEN-LAST:event_TablaProductosMouseClicked

    private void btnLimpiarPROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarPROMouseClicked
        // TODO add your handling code here:
        txtProductoIDPRO.setText("");
        txtNombrePRO.setText("");
        txtPrecioPRO.setText("");
        txtCantidadPRO.setText("");
    }//GEN-LAST:event_btnLimpiarPROMouseClicked

    private void btnEliminarPROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPROMouseClicked
//        // TODO add your handling code here:
//        if (txtProductoIDPRO.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Introduzca el producto que se eliminará");
//        }else{
//            try{
//                Con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/SellerTBL","postgres","1234");
//                String Pid = txtProductoIDPRO.getText();
//                String Query = "Delete from User1.PRODUCTTBL where PROID="+Pid;
//                Statement Add = Con.createStatement();
//                Add.execute(Query);
//                SelectSeller();
//                JOptionPane.showMessageDialog(this, "Producto eleimiando satisfactoriamente");
//            }catch(Exception e){
//                e.printStackTrace();
//            }
//
//        }
    }//GEN-LAST:event_btnEliminarPROMouseClicked

    private void btnAgregarPROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPROMouseClicked
        // TODO add your handling code here:

//        if(txtProductoIDPRO.getText().isEmpty()|| txtNombrePRO.getText().isEmpty()||txtPrecioPRO.getText().isEmpty()||txtCantidadPRO.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Informacion Faltante");
//        }
//        else{
//            try {
//                //Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Supermarket","null","null");
//                Con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/SellerTBL","postgres","1234");
//                PreparedStatement add = Con.prepareStatement("insert into PRODUCTTBL values(?,?,?,?,?)");
//                add.setInt(1, Integer.valueOf(txtProductoIDPRO.getText()));
//                add.setString(2, txtNombrePRO.getText());
//                add.setInt(3, Integer.valueOf(txtCantidadPRO.getText()));
//                add.setInt(4, Integer.valueOf(txtPrecioPRO.getText()));
//                add.setString(5, CatCB.getSelectedItem().toString());
//                int row = add.executeUpdate();
//                JOptionPane.showMessageDialog(this, "Producto agregado con exito");
//                Con.close();
//                SelectSeller();
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
    }//GEN-LAST:event_btnAgregarPROMouseClicked

    private void btnEditarPROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPROMouseClicked
//        // TODO add your handling code here:
//        if(txtProductoIDPRO.getText().isEmpty()||txtNombrePRO.getText().isEmpty()||txtCantidadPRO.getText().isEmpty()||txtPrecioPRO.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Informacion faltante");
//        }else{
//            try{
//                Con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/SellerTBL","postgres","1234");
//                String Query = "Update User1.PRODUCTTBL set PRONAME='"+txtNombrePRO.getText()+"'"+",PROQTY='"+txtCantidadPRO.getText()+""+",PROPRICE='"+txtPrecioPRO.getText()+""+",PROCAT='"+CatCB.getSelectedItem().toString()+"'"+"where PROID="+txtProductoIDPRO.getText();
//                Statement Add = Con.createStatement();
//                Add.executeUpdate(Query);
//                JOptionPane.showMessageDialog(this, "Producto actualizado");
//                SelectSeller();
//            }catch(SQLException e){
//                e.printStackTrace();
//            }
//        }
    }//GEN-LAST:event_btnEditarPROMouseClicked

    private void btnRegresarPROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarPROMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarPROMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxPRO;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnAgregarPRO;
    private javax.swing.JButton btnEditarPRO;
    private javax.swing.JButton btnEliminarPRO;
    private javax.swing.JButton btnExaminarPRO;
    private javax.swing.JButton btnLimpiarPRO;
    private javax.swing.JButton btnRegresarPRO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_fotoPRO;
    private javax.swing.JTextField txtCantidadPRO;
    private javax.swing.JTextField txtNombrePRO;
    private javax.swing.JTextField txtPrecioPRO;
    private javax.swing.JTextField txtProductoIDPRO;
    // End of variables declaration//GEN-END:variables
}
