/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Mis Documentos
 */
public class RegistroEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form Vendedor
     */
    public RegistroEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmpleadoIdRE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCedulaRE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtContraseñaRE = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnAgregarRE = new javax.swing.JButton();
        btnEditarRE = new javax.swing.JButton();
        btnEliminarRE = new javax.swing.JButton();
        btnLimpiarRE = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNombreRE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtApellidoRE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDireccionRE = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCorreoRE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCelularRE = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtUsuarioRE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnRegresarRE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(35, 155, 86));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("REGISTRO DE EMPLEADOS");

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("Empleado ID:");

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("Cedula:");

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("Contraseña:");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnAgregarRE.setBackground(new java.awt.Color(255, 102, 0));
        btnAgregarRE.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnAgregarRE.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarRE.setText("Agregar");
        btnAgregarRE.setBorder(null);
        btnAgregarRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarREMouseClicked(evt);
            }
        });

        btnEditarRE.setBackground(new java.awt.Color(255, 102, 0));
        btnEditarRE.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnEditarRE.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarRE.setText("Editar");
        btnEditarRE.setBorder(null);
        btnEditarRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarREMouseClicked(evt);
            }
        });

        btnEliminarRE.setBackground(new java.awt.Color(255, 102, 0));
        btnEliminarRE.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnEliminarRE.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarRE.setText("Eliminar");
        btnEliminarRE.setBorder(null);
        btnEliminarRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarREMouseClicked(evt);
            }
        });

        btnLimpiarRE.setBackground(new java.awt.Color(255, 102, 0));
        btnLimpiarRE.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnLimpiarRE.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarRE.setText("Limpiar");
        btnLimpiarRE.setBorder(null);
        btnLimpiarRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarREMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnAgregarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnEditarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnEliminarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnLimpiarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setText("Nombre:");

        jLabel9.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 51));
        jLabel9.setText("Apellido:");

        jLabel10.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 51));
        jLabel10.setText("Dirección:");

        jLabel11.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 51));
        jLabel11.setText("Correo:");

        jLabel12.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 51));
        jLabel12.setText("Celular:");

        jLabel13.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 51));
        jLabel13.setText("Usuario:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUsuarioRE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCedulaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(31, 31, 31)
                            .addComponent(txtEmpleadoIdRE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombreRE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApellidoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtContraseñaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(26, 26, 26)
                                .addComponent(txtDireccionRE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(26, 26, 26)
                                    .addComponent(txtCelularRE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCorreoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtEmpleadoIdRE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDireccionRE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtCedulaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoRE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtNombreRE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelularRE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txtApellidoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtContraseñaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(txtUsuarioRE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        btnRegresarRE.setBackground(new java.awt.Color(255, 102, 0));
        btnRegresarRE.setFont(new java.awt.Font("Poppins SemiBold", 1, 48)); // NOI18N
        btnRegresarRE.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarRE.setText("<");
        btnRegresarRE.setBorder(null);
        btnRegresarRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarREMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getAddbtn2() {
        return btnRegresarRE;
    }

    public void setAddbtn2(JButton Addbtn2) {
        this.btnRegresarRE = Addbtn2;
    }

    public JButton getBtnAgregarRE() {
        return btnAgregarRE;
    }

    public void setBtnAgregarRE(JButton btnAgregarRE) {
        this.btnAgregarRE = btnAgregarRE;
    }

    public JButton getBtnEditarRE() {
        return btnEditarRE;
    }

    public void setBtnEditarRE(JButton btnEditarRE) {
        this.btnEditarRE = btnEditarRE;
    }

    public JButton getBtnEliminarRE() {
        return btnEliminarRE;
    }

    public void setBtnEliminarRE(JButton btnEliminarRE) {
        this.btnEliminarRE = btnEliminarRE;
    }

    public JButton getBtnLimpiarRE() {
        return btnLimpiarRE;
    }

    public void setBtnLimpiarRE(JButton btnLimpiarRE) {
        this.btnLimpiarRE = btnLimpiarRE;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JTextField getTxtApellidoRE() {
        return txtApellidoRE;
    }

    public void setTxtApellidoRE(JTextField txtApellidoRE) {
        this.txtApellidoRE = txtApellidoRE;
    }

    public JTextField getTxtCedulaRE() {
        return txtCedulaRE;
    }

    public void setTxtCedulaRE(JTextField txtCedulaRE) {
        this.txtCedulaRE = txtCedulaRE;
    }

    public JTextField getTxtCelularRE() {
        return txtCelularRE;
    }

    public void setTxtCelularRE(JTextField txtCelularRE) {
        this.txtCelularRE = txtCelularRE;
    }

    public JTextField getTxtContraseñaRE() {
        return txtContraseñaRE;
    }

    public void setTxtContraseñaRE(JTextField txtContraseñaRE) {
        this.txtContraseñaRE = txtContraseñaRE;
    }

    public JTextField getTxtCorreoRE() {
        return txtCorreoRE;
    }

    public void setTxtCorreoRE(JTextField txtCorreoRE) {
        this.txtCorreoRE = txtCorreoRE;
    }

    public JTextField getTxtDireccionRE() {
        return txtDireccionRE;
    }

    public void setTxtDireccionRE(JTextField txtDireccionRE) {
        this.txtDireccionRE = txtDireccionRE;
    }

    public JTextField getTxtEmpleadoIdRE() {
        return txtEmpleadoIdRE;
    }

    public void setTxtEmpleadoIdRE(JTextField txtEmpleadoIdRE) {
        this.txtEmpleadoIdRE = txtEmpleadoIdRE;
    }

    public JTextField getTxtNombreRE() {
        return txtNombreRE;
    }

    public void setTxtNombreRE(JTextField txtNombreRE) {
        this.txtNombreRE = txtNombreRE;
    }
    
    
    
    
    private void btnEditarREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarREMouseClicked
        // TODO add your handling code here:
//        if(txtEmpleadoIdRE.getText().isEmpty()||txtCedulaRE.getText().isEmpty()||txtContraseñaRE.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Informacion faltante");
//        }else{
//            try{
//                Con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/SellerTBL","postgres","1234");
//                String Query = "Update User1.SELLERTBL set SELNAME='"+txtCedulaRE.getText()+"'"+",SELPASS='"+txtContraseñaRE.getText()+"'"+",SELGENDER='"+GenderCB.getSelectedItem().toString()+"'"+"where SELID="+txtEmpleadoIdRE.getText();
//                Statement Add = Con.createStatement();
//                Add.executeUpdate(Query);
//                JOptionPane.showMessageDialog(this, "Vendedror actualizado");
//                SelectSeller();
//            }catch(SQLException e){
//                e.printStackTrace();
//            }
//        }

    }//GEN-LAST:event_btnEditarREMouseClicked

    private void btnAgregarREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarREMouseClicked
        // TODO add your handling code here:
//        if(txtEmpleadoIdRE.getText().isEmpty()|| txtCedulaRE.getText().isEmpty()||txtContraseñaRE.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Informacion Faltante");
//        }
//        else{
//            try {
//                //Con = DriverManager.getConnection("jdbc:derby://localhost:1527/Supermarket","null","null");
//                Con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/SellerTBL","postgres","1234");
//                PreparedStatement add = Con.prepareStatement("insert into SELLERTBL values(?,?,?,?)");
//                add.setInt(1, Integer.valueOf(txtEmpleadoIdRE.getText()));
//                add.setString(2, txtCedulaRE.getText());
//                add.setString(3, txtContraseñaRE.getText());
//                add.setString(4, GenderCB.getSelectedItem().toString());
//                int row = add.executeUpdate();
//                JOptionPane.showMessageDialog(this, "Vendedor agregado con exito");
//                Con.close();
//                SelectSeller();
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
    }//GEN-LAST:event_btnAgregarREMouseClicked

    private void btnEliminarREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarREMouseClicked
        // TODO add your handling code here:
//        if (txtEmpleadoIdRE.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Introduzca la vendedora que se eliminará");
//        }else{
//            try{
//                Con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/SellerTBL","postgres","1234");
//                String Sid = txtEmpleadoIdRE.getText();
//                String Query = "Delete from User1.SELLERTBL where Selid="+Sid;
//                Statement Add = Con.createStatement();
//                Add.execute(Query);
//                SelectSeller();
//                JOptionPane.showMessageDialog(this, "vendedor eleimiando satisfactoriamente");
//            }catch(Exception e){
//                e.printStackTrace();
//            }
//
//        }

    }//GEN-LAST:event_btnEliminarREMouseClicked

    private void btnLimpiarREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarREMouseClicked
        // TODO add your handling code here:
        txtEmpleadoIdRE.setText("");
        txtCedulaRE.setText("");
        txtContraseñaRE.setText("");
        txtNombreRE.setText("");
        txtApellidoRE.setText("");
        txtDireccionRE.setText("");
        txtCorreoRE.setText("");
        txtCelularRE.setText("");
        
    }//GEN-LAST:event_btnLimpiarREMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnRegresarREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarREMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarREMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRE;
    private javax.swing.JButton btnEditarRE;
    private javax.swing.JButton btnEliminarRE;
    private javax.swing.JButton btnLimpiarRE;
    private javax.swing.JButton btnRegresarRE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtApellidoRE;
    private javax.swing.JTextField txtCedulaRE;
    private javax.swing.JTextField txtCelularRE;
    private javax.swing.JTextField txtContraseñaRE;
    private javax.swing.JTextField txtCorreoRE;
    private javax.swing.JTextField txtDireccionRE;
    private javax.swing.JTextField txtEmpleadoIdRE;
    private javax.swing.JTextField txtNombreRE;
    private javax.swing.JTextField txtUsuarioRE;
    // End of variables declaration//GEN-END:variables
}
