/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Mis Documentos
 */
public class Venta extends javax.swing.JFrame {

    /**
     * Creates new form Venta
     */
    public Venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidFacturaVE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreVE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidadVE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxFiltrarVE = new javax.swing.JComboBox<>();
        UpdateBtn = new javax.swing.JButton();
        btnAgregarVE = new javax.swing.JButton();
        btnActualizarVE = new javax.swing.JButton();
        btnBorrarVE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVE = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BillTxt = new javax.swing.JTextArea();
        GrdTotalLBL = new javax.swing.JLabel();
        btnFiltrarVE = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JBLLogout1 = new javax.swing.JLabel();
        btnRegresarVE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(35, 155, 86));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("PUNTO DE FACTURACION");

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 51));
        jLabel2.setText("ID de Factura:");

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 51));
        jLabel4.setText("Cantidad:");

        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("Filtrar Por:");

        ComboBoxFiltrarVE.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxFiltrarVEItemStateChanged(evt);
            }
        });
        ComboBoxFiltrarVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBoxFiltrarVEMouseClicked(evt);
            }
        });

        UpdateBtn.setBackground(new java.awt.Color(255, 102, 0));
        UpdateBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setText("Imprimir");
        UpdateBtn.setBorder(null);
        UpdateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBtnMouseClicked(evt);
            }
        });

        btnAgregarVE.setBackground(new java.awt.Color(255, 102, 0));
        btnAgregarVE.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnAgregarVE.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarVE.setText("Agregar a la Factura");
        btnAgregarVE.setBorder(null);
        btnAgregarVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarVEMouseClicked(evt);
            }
        });

        btnActualizarVE.setBackground(new java.awt.Color(255, 102, 0));
        btnActualizarVE.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnActualizarVE.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarVE.setText("Actualizar");
        btnActualizarVE.setBorder(null);
        btnActualizarVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarVEMouseClicked(evt);
            }
        });

        btnBorrarVE.setBackground(new java.awt.Color(255, 102, 0));
        btnBorrarVE.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnBorrarVE.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarVE.setText("Borrar");
        btnBorrarVE.setBorder(null);
        btnBorrarVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarVEMouseClicked(evt);
            }
        });

        TablaVE.setBackground(new java.awt.Color(255, 255, 255));
        TablaVE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CANTIDAD", "PRECIO", "CATEGORIA"
            }
        ));
        TablaVE.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablaVE.setRowHeight(25);
        TablaVE.setSelectionBackground(new java.awt.Color(255, 102, 0));
        TablaVE.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TablaVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaVEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaVE);

        jLabel8.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 51));
        jLabel8.setText("Lista de Productos");

        BillTxt.setColumns(20);
        BillTxt.setFont(new java.awt.Font("Futura", 2, 14)); // NOI18N
        BillTxt.setRows(5);
        jScrollPane2.setViewportView(BillTxt);

        GrdTotalLBL.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        GrdTotalLBL.setForeground(new java.awt.Color(255, 102, 51));
        GrdTotalLBL.setText("$:");

        btnFiltrarVE.setBackground(new java.awt.Color(255, 102, 0));
        btnFiltrarVE.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnFiltrarVE.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltrarVE.setText("Filtrar");
        btnFiltrarVE.setBorder(null);
        btnFiltrarVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarVEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(103, 103, 103))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombreVE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidadVE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtidFacturaVE, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnAgregarVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarVE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxFiltrarVE, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrarVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizarVE, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(GrdTotalLBL)
                .addGap(55, 55, 55)
                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtidFacturaVE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreVE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtCantidadVE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ComboBoxFiltrarVE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizarVE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFiltrarVE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GrdTotalLBL))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarVE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrarVE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        JBLLogout1.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        JBLLogout1.setForeground(new java.awt.Color(255, 255, 255));
        JBLLogout1.setText("Logout");
        JBLLogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBLLogout1MouseClicked(evt);
            }
        });

        btnRegresarVE.setBackground(new java.awt.Color(255, 102, 0));
        btnRegresarVE.setFont(new java.awt.Font("Poppins SemiBold", 1, 48)); // NOI18N
        btnRegresarVE.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresarVE.setText("<");
        btnRegresarVE.setBorder(null);
        btnRegresarVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarVEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(JBLLogout1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresarVE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresarVE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBLLogout1)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxFiltrarVEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxFiltrarVEItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboBoxFiltrarVEItemStateChanged

    private void ComboBoxFiltrarVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxFiltrarVEMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboBoxFiltrarVEMouseClicked

    private void UpdateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBtnMouseClicked
//        try{
//            BillTxt.print();
//        }catch (Exception e){
//
//        }
    }//GEN-LAST:event_UpdateBtnMouseClicked

    private void btnAgregarVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarVEMouseClicked
//        // TODO add your handling code here:
//        if(ProQty.getText().isEmpty()||ProName.getText().isEmpty()){
//            JOptionPane.showMessageDialog(this, "Informacion Faltante");
//
//        }
//        else if(AvailQty <= Integer.valueOf(ProQty.getText())){
//            JOptionPane.showMessageDialog(this, "no hay suficiente en stock");
//        }
//
//        else{
//            i++;
//            ProduTotal = Uprice * Integer.valueOf(ProQty.getText());
//            GrdTotal = GrdTotal+ProduTotal;
//            if(i == 1){
//                BillTxt.setText(BillTxt.getText()+"    =========== Factura ============\n"+" NUM      PRODUCT    PRICE     QUANTITY    TOTAL \n "+i+"    "+ProName.getText()+"    "+Uprice+"    "+ProQty.getText()+"     "+ProduTotal+"\n");
//            }else{
//                BillTxt.setText(BillTxt.getText()+i+"    "+ProName.getText()+"    "+Uprice+"    "+ProQty.getText()+"     "+ProduTotal+"\n");
//            }
//            GrdTotalLBL.setText("$"+GrdTotal);
//            update();
//        }
//
    }//GEN-LAST:event_btnAgregarVEMouseClicked

    private void btnActualizarVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarVEMouseClicked

    }//GEN-LAST:event_btnActualizarVEMouseClicked

    private void btnBorrarVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarVEMouseClicked
        // TODO add your handling code here:
//        Billid.setText("");
//        ProName.setText("");
//        //ProPrice.setText("");
//        ProQty.setText("");
    }//GEN-LAST:event_btnBorrarVEMouseClicked

    private void TablaVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaVEMouseClicked
//        // TODO add your handling code here:
//        DefaultTableModel model = (DefaultTableModel)ProductTable.getModel();
//        int Myindex = ProductTable.getSelectedRow();
//        Prid = Integer.valueOf(model.getValueAt(Myindex, 0).toString());
//        ProName.setText(model.getValueAt(Myindex, 1).toString());
//        AvailQty = Integer.valueOf(model.getValueAt(Myindex, 2).toString());
//        newQty = AvailQty - Integer.valueOf(ProQty.getText());
//        Uprice = Double.valueOf(model.getValueAt(Myindex, 3).toString());

        //ProQty.setText(model.getValueAt(Myindex, 2).toString());
        //ProPrice.setText(model.getValueAt(Myindex, 3).toString());
    }//GEN-LAST:event_TablaVEMouseClicked

    private void btnFiltrarVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarVEMouseClicked
        // TODO add your handling code here:
//        try{
//            Con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/SellerTBL","postgres","1234");
//            St = Con.createStatement();
//            Rs = St.executeQuery("Select * from User1.CATEGORYTBL where CATNAME='"+CatCB.getSelectedItem.toString()+"'");
//            ProductTable.setModel(DbUtils.resulSetToTableModel(Rs));
//        }catch(Exception e){
//            e.printStackTrace();
//        }
//        }
    }//GEN-LAST:event_btnFiltrarVEMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
//        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void JBLLogout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBLLogout1MouseClicked
        // TODO add your handling code here:
//        new Login().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_JBLLogout1MouseClicked

    private void btnRegresarVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarVEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarVEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BillTxt;
    private javax.swing.JComboBox<String> ComboBoxFiltrarVE;
    private javax.swing.JLabel GrdTotalLBL;
    private javax.swing.JLabel JBLLogout1;
    private javax.swing.JTable TablaVE;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton btnActualizarVE;
    private javax.swing.JButton btnAgregarVE;
    private javax.swing.JButton btnBorrarVE;
    private javax.swing.JButton btnFiltrarVE;
    private javax.swing.JButton btnRegresarVE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCantidadVE;
    private javax.swing.JTextField txtNombreVE;
    private javax.swing.JTextField txtidFacturaVE;
    // End of variables declaration//GEN-END:variables
}
